language: cpp
sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - clang-3.7
compiler:
    - gcc-5
    - clang-3.7

before_script:
    - mkdir build
    - cd build
    - cmake -DWITH_QT5=false ..

script:
    - make
    - make -j2 tests
    - make check
