language: cpp
sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libboost1.55-all-dev

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake -DWITH_QT5=false ..

script:
    - make
    - make check
